micronaut:
  application:
    name: google-drive-upload

  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths:
          - "classpath:static/css"

oci-google-drive:
  application:
    dir-key: "benefits"
    name: "OCI Google Drive Uploader"
    scopes:
      - "https://www.googleapis.com/auth/drive.file"
